version: '3.3'
services:
  rabbitmq-management:
    container_name: rabbitmq-test
    image: "rabbitmq:management"
    ports:
      - "5673:5673"
      - "5672:5672"
      - "15672:15672"
    network_mode: host
